name: vt
channels:
- conda-forge
- anaconda
- free
- defaults
dependencies:
- apptools
- configobj
- envisage
- freetype
- libpng
- mayavi
- mkl
- numpy
- openssl
- pip
- pyface
- pygments
- pyyaml
- readline
- python
- pyqt
- setuptools
- sip
- six
- sqlite
- tk
- wheel
- yaml
- zlib
- cycler
- matplotlib
- nibabel
- pyparsing
- python-dateutil
- pytz
- scipy