name: vt
channels:
- conda-forge
dependencies:
- apptools
- configobj
- envisage
- freetype
- libpng
- mkl
- numpy
- openssl
- pip
- pyface
- pygments
- pyyaml
- readline
- python=3.12.2
- pyqt=5.15.9
- pyqt5-sip=12.12.2
- readline
- mayavi=4.8.1
- setuptools
- sip
- six
- sqlite
- tk
- wheel
- yaml
- zlib
- cycler
- matplotlib
- nibabel
- pyparsing
- python-dateutil
- pytz
- scipy
- traits=6.4.3
- traitlets=5.14.3
- traitsui=8.0.0
- vtk =9.2.6
- vtk-base=9.2.6
