name: vt
channels:
  - conda-forge
dependencies:
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - aom=3.8.2
  - apptools=5.1.0
  - asttokens=2.4.1
  - attrs=23.2.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.18.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - comm=0.2.2
  - configobj=5.0.8
  - contourpy=1.2.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - dcm2niix=1.0.20240202
  - debugpy=1.8.1
  - decorator=5.1.1
  - double-conversion=3.3.0
  - eigen=3.4.0
  - envisage=6.0.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=6.1.1
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - freeglut=3.2.2
  - freetype=2.13.3
  - frozenlist=1.4.1
  - gettext=0.21.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.82.2
  - glib-tools=2.82.2
  - graphite2=1.3.13
  - gsl=2.7
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h2=4.2.0
  - harfbuzz=8.3.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.6
  - ihm=1.0
  - imageio=2.37.0
  - imath=3.1.12
  - imp=2.20.1
  - importlib-metadata=7.0.2
  - importlib_metadata=7.0.2
  - importlib_resources=6.3.0
  - intel-openmp=2024.0.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jasper=4.2.2
  - jedi=0.19.1
  - joblib=1.4.2
  - jsoncpp=1.9.5
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - khronos-opencl-icd-loader=2023.04.17
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240116.1
  - libaec=1.1.3
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=19.1.7
  - libclang13=19.1.7
  - libcurl=8.12.1
  - libdeflate=1.23
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflang=5.0.0
  - libglib=2.82.2
  - libhwloc=2.11.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libitk=5.4.2
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.6.4
  - libnetcdf=4.9.2
  - libogg=1.3.5
  - libopenblas=0.3.26
  - libopencv=4.9.0
  - libopenvino=2023.3.0
  - libopenvino-auto-batch-plugin=2023.3.0
  - libopenvino-auto-plugin=2023.3.0
  - libopenvino-hetero-plugin=2023.3.0
  - libopenvino-intel-cpu-plugin=2023.3.0
  - libopenvino-intel-gpu-plugin=2023.3.0
  - libopenvino-ir-frontend=2023.3.0
  - libopenvino-onnx-frontend=2023.3.0
  - libopenvino-paddle-frontend=2023.3.0
  - libopenvino-pytorch-frontend=2023.3.0
  - libopenvino-tensorflow-frontend=2023.3.0
  - libopenvino-tensorflow-lite-frontend=2023.3.0
  - libopus=1.3.1
  - libpng=1.6.47
  - libprotobuf=4.25.2
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.11.1
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-meta=5.0.0
  - loguru=0.7.2
  - lxml=5.1.0
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.7
  - mayavi=4.8.1
  - mkl=2024.0.0
  - mpfr=4.2.1
  - mpi=1.0
  - mpir=3.0.0
  - msgpack-python=1.0.7
  - msmpi=10.1.1
  - msys2-conda-epoch=20160418
  - multidict=6.0.5
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - nibabel=5.2.1
  - nilearn=0.11.1
  - nlohmann_json=3.11.2
  - numpy=1.26.4
  - openexr=3.2.2
  - openh264=2.4.1
  - openjpeg=2.5.3
  - openmp=5.0.0
  - openssl=3.4.1
  - packaging=24.0
  - pandas=2.2.2
  - parso=0.8.4
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.4
  - platformdirs=4.2.1
  - ply=3.11
  - pooch=1.8.2
  - proj=9.3.1
  - prompt-toolkit=3.0.42
  - protobuf=4.25.2
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pugixml=1.14
  - pure_eval=0.2.2
  - pycparser=2.22
  - pyface=8.0.0
  - pygments=2.17.2
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyreadline3=3.4.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyvista=0.44.2
  - pyvistaqt=0.11.2
  - pywin32=306
  - pyyaml=6.0.1
  - pyzmq=26.0.2
  - qt-main=5.15.8
  - qtpy=2.4.3
  - requests=2.32.3
  - rmf=1.6.0
  - scikit-learn=1.6.1
  - scipy=1.12.0
  - scooby=0.10.0
  - setuptools=69.2.0
  - simpleitk=2.4.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.2
  - stack_data=0.6.2
  - svt-av1=2.0.0
  - tbb=2021.13.0
  - tbb-devel=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4
  - traitlets=5.14.3
  - traits=6.4.3
  - traitsui=8.0.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - urllib3=2.3.0
  - utfcpp=4.0.5
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - vtk=9.2.6
  - vtk-base=9.2.6
  - wcwidth=0.2.13
  - wheel=0.42.0
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - wslink=1.12.4
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - antspyx==0.5.4
      - patsy==1.0.1
      - statsmodels==0.14.4
      - webcolors==24.11.1
